# Generated by Django 4.0.3 on 2022-03-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=40)),
                ('cuerpo', models.TextField(verbose_name='')),
                ('imagen', models.FileField(upload_to='')),
            ],
        ),
    ]
