# Generated by Django 4.0.3 on 2022-03-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0004_post_categoria_alter_post_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.TextField(default='', verbose_name=''),
        ),
    ]
