# Generated by Django 4.0.3 on 2022-03-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0005_comment_remove_post_imagen_post_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
    ]
