# Generated by Django 4.0.3 on 2022-03-29 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0007_remove_post_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='autor',
            field=models.CharField(default=' ', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='cuerpo',
            field=models.TextField(default=' ', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
