# Generated by Django 4.0.3 on 2022-03-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0008_usuariocomun_comment_autor_comment_cuerpo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_comment_id',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
