# Generated by Django 4.0.3 on 2022-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0010_alter_post_email_alter_post_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultasSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('consulta', models.TextField(verbose_name='')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
