# Generated by Django 4.0.3 on 2022-04-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0015_alter_comment_post_comment_id_userabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_comment_id',
            field=models.CharField(max_length=30),
        ),
    ]
