# Generated by Django 4.0.3 on 2022-04-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0016_alter_comment_post_comment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
