# Generated by Django 4.0.3 on 2022-04-30 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0019_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
