# Generated by Django 4.0.3 on 2022-05-01 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0021_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenesposts')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBlog.post')),
            ],
        ),
    ]
