# Generated by Django 4.0.3 on 2022-05-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0022_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='userabout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='UserAbout',
        ),
    ]
