# Generated by Django 4.0.3 on 2022-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0023_remove_chat_recipient_remove_userabout_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesposts'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
