# Generated by Django 4.0.3 on 2022-05-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0024_post_imagen_post_subtitulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultasSoporte',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
